# MYSQL + BACKEND (api) + FRONTEND (REACT)
# for running everything use : docker-compose up -d
services:

#        -------------------------- database -------------------------
  # Northwind database (mysql) service:
  northwind-database-service:
    
    #image name to create from Dockerfile:
    image: mindalizeev/northwind-database-image:1.0

    #Build the image if not exists , the instruction are inside the directory
    build: ./Database

    #Container name:
    container_name: northwind-database-container

    #port binding (host:container)
    ports:
      - 3306:3306

    #Enviorment variables needed by MySQL:
    environment:
      MYSQL_HOST: localhost #internally for the container
      MYSQL_DATABASE: northwind
      MYSQL_USER: Alice
      MYSQL_PASSWORD: Wonderland
      MYSQL_ROOT_PASSWORD: Wonderland #needed by mysql

    #On crash - restart continaer , unless manually stopped
    restart: unless-stopped

    #Database volumes:
    #named volume
    volumes:
      - northwind:/var/lib/mysql

#        -------------------------- backend  -------------------------

  northwind-backend-service:

    #image name
    image: mindalizeev/northwind-backend-image:1.0

    #build the image (if not exists) from specified Dockerfile location:
    build: ./backend

    #container name:
    container_name: northwind-backend-container

    #port binding (host:container):
    ports:
      - 5000:4000

    #Environment variables
    environment:
      PORT: 4000
      MYSQL_HOST: northwind-database-service #above database service is the name
      MYSQL_DATABASE: northwind
      MYSQL_User: Alice
      MYSQL_PASSWORD: Wonderland

    #On crash
    restart: unless-stopped

    #host volumes
    volumes:
      - ./backend:/app

    #On which service we are depnding on (starting/stopping order)
    depends_on:
      - northwind-database-service

#        -------------------------- frontend -------------------------

  northwind-frontend-service:

    image: mindalizeev/northwind-frontend-image:1.0
    build: ./Frontend
    container_name: northwind-frontend-container
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./Frontend:/app
    depends_on:
      - northwind-backend-service
# ------------------------------------------------------------------------------------------

volumes:
  northwind: